### ISSUE TITLE
With our Core/ASP.NET Core project we need to include the .dolittle folder as content for building output

### ISSUE THREAD

**Issue by einari** [dolittle-boilerplates/CSharp.BoundedContext#4]
In addition to the `wwwroot` folder, we need to have the `.dolittle` folder included as content for output. The `.csproj` file needs to have this:

```xml
  <ItemGroup>
    <Folder Include="wwwroot\" />
    <Content Include=".dolittle\**\*" CopyToPublishDirectory="Always"/>
  </ItemGroup>
```

**Comment by woksin** [comment]
The Core project is not necessarily a Web project, we shouldn't include wwwroot if it's not?

**Comment by einari** [comment]
True - but our template is ASP.NET based right now and assuming this for now. 
It is a temporary solution to a problem we don't want to have :)

**Comment by einari** [comment]
Hang on...   This has changed..

**Comment by woksin** [comment]
It's not ASP.NET based https://github.com/dolittle-boilerplates/CSharp.BoundedContext/blob/master/Content/Core/Core.csproj

**Comment by einari** [comment]
I assumed it had ASP.NET references and `Program.cs` and `Startup.cs` was set up with ASP.NET Core and all. Then this should be done in the right place.    Lets discuss this then!

**Comment by woksin** [comment]
I was thinking of adding this when we also add the suppor for
$ dolittle create boundedcontext SomeBoundedContext

$ Interaction layer? [yes | no]
$ What kind of interaction layer ...

**Comment by woksin** [comment]
Let's not assume that all dolittle-based application will have a web-interaction layer (that's atleast the idea)

**Comment by einari** [comment]
Totally agree. Lets design this whole thing.  Hold off on this then
