### ISSUE TITLE
Make a working boilerplate end-to-end for current version

### ISSUE THREAD

**Issue by einari** [dolittle-boilerplates/CSharp.BoundedContext#5]

**Comment by einari** [comment]
Our goal is to separate out ASP.NET and have a core bounded context. Right now, since the boilerplate does not generate something that just runs - suggest we do the following:

- [ ] Put in ASP.NET - Dolittle.AspNetCore - and configure it properly.
- [ ] Put in place necessary **.dolittle** files
- [ ] Remove NullBindings - depends on us pushing from MyGet the latest and greatest
- [ ] Add a Web folder - project - configure using Aurelia for now - let it output `wwwroot` to `Core/wwwroot`

**Comment by woksin** [comment]
The boilerplates needs to be synchronized with what's on nuget. Currently there is quite a bit of difference between our local "dev" packages and what's on nuget.

**Comment by einari** [comment]
Yup. I was thinking we could just push what we have on MyGet right now and make the boilerplate against that. Feel confident that what we have on MyGet is more stable than whats on NuGet anyways.

**Comment by woksin** [comment]
I agree, but let's push that to monday. I'm going to work on some bugs over the weekend :)

**Comment by woksin** [comment]
But yeah, I think that providing a boilerplate for an end-to-end solution with web-interaction layer is important and something that we should do

**Comment by einari** [comment]
Yup.. For now - since we've got our plate full - lets just focus on whats the shortest path to goal. So make this our end-to-end and assume Web is there and make the hard choice of Aurelia for now. The plans we have to make this more interactive and better from the tooling side will come and we can make the different interaction boilerplates on top.
